import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { QUEUE_TOPOLOGY, type QueueDefinition } from './queue-topology.js';

/**
 * `contracts/relay-interfaces.md` §5: `QUEUE_TOPOLOGY` → ElasticMQ's HOCON.
 * `infrastructure/elasticmq/queues.conf` is generated by this and committed,
 * never hand-edited (research.md §4) — `render-elasticmq-config.spec.ts`
 * (T017) re-renders and diffs against the committed file so the two cannot
 * drift silently.
 */
function renderQueueBlock(queue: QueueDefinition): string {
  return [
    `  ${queue.name} {`,
    `    defaultVisibilityTimeout = 30 seconds`,
    `    delay = 0 seconds`,
    `    receiveMessageWait = 0 seconds`,
    `    deadLettersQueue {`,
    `      name = "${queue.dlqName}"`,
    `      maxReceiveCount = ${String(queue.maxReceiveCount)}`,
    `    }`,
    `  }`,
    `  ${queue.dlqName} {`,
    `    defaultVisibilityTimeout = 30 seconds`,
    `  }`,
  ].join('\n');
}

export function renderElasticmqConfig(topology: readonly QueueDefinition[]): string {
  const queueBlocks = topology.map(renderQueueBlock).join('\n');
  return ['queues {', queueBlocks, '}', 'messages-storage {', '  enabled = true', '}', ''].join(
    '\n',
  );
}

/** Exported so the drift-check test (T017) never hardcodes a second copy of this path. */
export const RENDERED_CONFIG_PATH = fileURLToPath(
  new URL('../../../../infrastructure/elasticmq/queues.conf', import.meta.url),
);

const isMain = process.argv[1] === fileURLToPath(import.meta.url);

if (isMain) {
  mkdirSync(dirname(RENDERED_CONFIG_PATH), { recursive: true });
  writeFileSync(RENDERED_CONFIG_PATH, renderElasticmqConfig(QUEUE_TOPOLOGY));
  console.log(`Wrote ${RENDERED_CONFIG_PATH}`);
}
