config:
  infrastructure:vpsHost:
    secure: AAABALtbbu9n6IFzsPzX3b1oTs2Xd9YiuUnPvr34DAIZQGTrXHWY7w7PrCU8
  infrastructure:vpsSshUser: deploy
  infrastructure:vpsSshPrivateKey:
    secure: AAABAPEFMBOGsepp5bB9x98Ja309knx8WnPsFAWtz5F3k5vAKGesygbf90gjZRmElmEzNoccZa28UR+C1yxXAjDv82ucQKy+5vLA64POUULqE+NV+wwV9Ae+Gdrd48cNc/fTYj9jleJBXUqwX3WFTTG4Ono/mE6HUH7QbOWvTsamxEjOnB8Ze9raSb3G4XTDUk8TKoqHGP5ygmCqVwDpE7Ctv7luEBxQ1Io7QQdPYGyEBeyCoSb8qrQQUG93D/NPoGA3+eLKqSn+R0YsY/oU+yJXnOPITsafObgx5Sphvir4jheHfKLDCPHCuNgWqlBhrutTcGqWmW/gQ/6CzWOG/puJZjPtm2jsKMRgpGlKJ5H6grS1EKzcTvZsku+Elk0RpLguu3cp8ukiMS07q+QmVnmk/Fg3N+aRGyGg9z1Wk3HBjoFcskuUXe8qB4J/p9Vcni0eqIXMVjb/OiSc9TW97UgRIlMnCf4l9E81AQdFnjarN6zQueOZHz8zqHN2XTXpwoDkRoRCN7kjP9GnNmzQi+2Sa20mPx/EY78liENVy3MTtGfAWb9t2CzR802Z2mA1D95Tist8vHwxTxjr0N7dd+NG1/ULlzwKggoi7fJrCg==
  infrastructure:postgresPassword:
    secure: AAABAPXy45x7R1WGkt7FIPdnBq6Ny9KFpkviwcveh/49Opfe2jAZCsm2MHCVR9fDI4sc/XdVs2tQ1b0qAVNiQagR5FLHqSDRp/q3KQ==
  infrastructure:apiPublishedPort: "8081"
