queues {
  outbox-relay-verification {
    defaultVisibilityTimeout = 30 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "outbox-relay-verification-dlq"
      maxReceiveCount = 5
    }
  }
  outbox-relay-verification-dlq {
    defaultVisibilityTimeout = 30 seconds
  }
}
messages-storage {
  enabled = true
}
